1 {{
2   "language": "Solidity",
3   "sources": {
4     "contracts/AllowListSale.sol": {
5       "content": "// SPDX-License-Identifier: MIT\n\npragma solidity ^0.8.0;\n\nimport \"@openzeppelin/contracts/utils/cryptography/MerkleProof.sol\";\nimport \"@openzeppelin/contracts/access/Ownable.sol\";\n\ninterface NFT {\n    function buy() external payable;\n\n    function buy(uint256 _quantity) external payable;\n}\n\n/**\n * @title AllowListSale Contract\n  Contract for allowlist sales on multiple contracts\n */\ncontract AllowListSale is Ownable {\n    mapping(address => bytes32) public merkleRoots;\n    mapping(address => uint256) private _requireAllowlist;\n\n    // Constructor\n    // @param _merkleRoot root of merkle tree\n    constructor(address _contractAddress, bytes32 _merkleRoot) {\n        merkleRoots[_contractAddress] = _merkleRoot;\n        _requireAllowlist[_contractAddress] = 1;\n    }\n\n    // @notice Is a given address allowlisted based on proof provided\n    // @param _proof Merkle proof\n    // @param _claimer address to check\n    // @param _contract NFT contract address\n    // @return Is allowlisted\n    function isOnAllowlist(\n        bytes32[] memory _proof,\n        address _claimer,\n        address _contract\n    ) public view returns (bool) {\n        bytes32 leaf = keccak256(abi.encodePacked(_claimer));\n        return MerkleProof.verify(_proof, merkleRoots[_contract], leaf);\n    }\n\n    function setMerkleRoot(address _contract, bytes32 _merkleRoot)\n        external\n        onlyOwner\n    {\n        merkleRoots[_contract] = _merkleRoot;\n    }\n\n    function allowlistMint(\n        address _contract,\n        bytes32[] memory _proof,\n        uint256 _quantity\n    ) external payable {\n        require(\n            (_requireAllowlist[_contract] == 1 &&\n                isOnAllowlist(_proof, _msgSender(), _contract)) ||\n                _requireAllowlist[_contract] == 0,\n            \"Unable to mint if not on the allowlist\"\n        );\n        if (_quantity == 0) {\n            NFT(_contract).buy{value: msg.value}();\n        } else {\n            NFT(_contract).buy{value: msg.value}(_quantity);\n        }\n    }\n\n    function publicMint(address _contract, uint256 _quantity) external payable {\n        require(\n            _requireAllowlist[_contract] == 0,\n            \"Public mint is not live yet\"\n        );\n        if (_quantity == 0) {\n            NFT(_contract).buy{value: msg.value}();\n        } else {\n            NFT(_contract).buy{value: msg.value}(_quantity);\n        }\n    }\n\n    function toggleAllowlistRequired(address _contract, uint256 _enabled)\n        public\n        onlyOwner\n    {\n        _requireAllowlist[_contract] = _enabled;\n    }\n\n    function batchSetContracts(\n        address[] memory _contracts,\n        uint256 _requireAllowList\n    ) external onlyOwner {\n        for (uint256 c = 0; c < _contracts.length; c += 1) {\n            _requireAllowlist[_contracts[c]] = _requireAllowList;\n        }\n    }\n}\n"
6     },
7     "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol": {
8       "content": "// SPDX-License-Identifier: MIT\n// OpenZeppelin Contracts v4.4.1 (utils/cryptography/MerkleProof.sol)\n\npragma solidity ^0.8.0;\n\n/**\n * @dev These functions deal with verification of Merkle Trees proofs.\n *\n * The proofs can be generated using the JavaScript library\n * https://github.com/miguelmota/merkletreejs[merkletreejs].\n * Note: the hashing algorithm should be keccak256 and pair sorting should be enabled.\n *\n * See `test/utils/cryptography/MerkleProof.test.js` for some examples.\n */\nlibrary MerkleProof {\n    /**\n     * @dev Returns true if a `leaf` can be proved to be a part of a Merkle tree\n     * defined by `root`. For this, a `proof` must be provided, containing\n     * sibling hashes on the branch from the leaf to the root of the tree. Each\n     * pair of leaves and each pair of pre-images are assumed to be sorted.\n     */\n    function verify(\n        bytes32[] memory proof,\n        bytes32 root,\n        bytes32 leaf\n    ) internal pure returns (bool) {\n        return processProof(proof, leaf) == root;\n    }\n\n    /**\n     * @dev Returns the rebuilt hash obtained by traversing a Merklee tree up\n     * from `leaf` using `proof`. A `proof` is valid if and only if the rebuilt\n     * hash matches the root of the tree. When processing the proof, the pairs\n     * of leafs & pre-images are assumed to be sorted.\n     *\n     * _Available since v4.4._\n     */\n    function processProof(bytes32[] memory proof, bytes32 leaf) internal pure returns (bytes32) {\n        bytes32 computedHash = leaf;\n        for (uint256 i = 0; i < proof.length; i++) {\n            bytes32 proofElement = proof[i];\n            if (computedHash <= proofElement) {\n                // Hash(current computed hash + current element of the proof)\n                computedHash = keccak256(abi.encodePacked(computedHash, proofElement));\n            } else {\n                // Hash(current element of the proof + current computed hash)\n                computedHash = keccak256(abi.encodePacked(proofElement, computedHash));\n            }\n        }\n        return computedHash;\n    }\n}\n"
9     },
10     "@openzeppelin/contracts/access/Ownable.sol": {
11       "content": "// SPDX-License-Identifier: MIT\n// OpenZeppelin Contracts v4.4.1 (access/Ownable.sol)\n\npragma solidity ^0.8.0;\n\nimport \"../utils/Context.sol\";\n\n/**\n * @dev Contract module which provides a basic access control mechanism, where\n * there is an account (an owner) that can be granted exclusive access to\n * specific functions.\n *\n * By default, the owner account will be the one that deploys the contract. This\n * can later be changed with {transferOwnership}.\n *\n * This module is used through inheritance. It will make available the modifier\n * `onlyOwner`, which can be applied to your functions to restrict their use to\n * the owner.\n */\nabstract contract Ownable is Context {\n    address private _owner;\n\n    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);\n\n    /**\n     * @dev Initializes the contract setting the deployer as the initial owner.\n     */\n    constructor() {\n        _transferOwnership(_msgSender());\n    }\n\n    /**\n     * @dev Returns the address of the current owner.\n     */\n    function owner() public view virtual returns (address) {\n        return _owner;\n    }\n\n    /**\n     * @dev Throws if called by any account other than the owner.\n     */\n    modifier onlyOwner() {\n        require(owner() == _msgSender(), \"Ownable: caller is not the owner\");\n        _;\n    }\n\n    /**\n     * @dev Leaves the contract without owner. It will not be possible to call\n     * `onlyOwner` functions anymore. Can only be called by the current owner.\n     *\n     * NOTE: Renouncing ownership will leave the contract without an owner,\n     * thereby removing any functionality that is only available to the owner.\n     */\n    function renounceOwnership() public virtual onlyOwner {\n        _transferOwnership(address(0));\n    }\n\n    /**\n     * @dev Transfers ownership of the contract to a new account (`newOwner`).\n     * Can only be called by the current owner.\n     */\n    function transferOwnership(address newOwner) public virtual onlyOwner {\n        require(newOwner != address(0), \"Ownable: new owner is the zero address\");\n        _transferOwnership(newOwner);\n    }\n\n    /**\n     * @dev Transfers ownership of the contract to a new account (`newOwner`).\n     * Internal function without access restriction.\n     */\n    function _transferOwnership(address newOwner) internal virtual {\n        address oldOwner = _owner;\n        _owner = newOwner;\n        emit OwnershipTransferred(oldOwner, newOwner);\n    }\n}\n"
12     },
13     "@openzeppelin/contracts/utils/Context.sol": {
14       "content": "// SPDX-License-Identifier: MIT\n// OpenZeppelin Contracts v4.4.1 (utils/Context.sol)\n\npragma solidity ^0.8.0;\n\n/**\n * @dev Provides information about the current execution context, including the\n * sender of the transaction and its data. While these are generally available\n * via msg.sender and msg.data, they should not be accessed in such a direct\n * manner, since when dealing with meta-transactions the account sending and\n * paying for execution may not be the actual sender (as far as an application\n * is concerned).\n *\n * This contract is only required for intermediate, library-like contracts.\n */\nabstract contract Context {\n    function _msgSender() internal view virtual returns (address) {\n        return msg.sender;\n    }\n\n    function _msgData() internal view virtual returns (bytes calldata) {\n        return msg.data;\n    }\n}\n"
15     }
16   },
17   "settings": {
18     "optimizer": {
19       "enabled": true,
20       "runs": 200
21     },
22     "outputSelection": {
23       "*": {
24         "*": [
25           "evm.bytecode",
26           "evm.deployedBytecode",
27           "devdoc",
28           "userdoc",
29           "metadata",
30           "abi"
31         ]
32       }
33     },
34     "metadata": {
35       "useLiteralContent": true
36     },
37     "libraries": {}
38   }
39 }}